version: "3.9" 
services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/dbdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

